declare module '*.jpg'
declare module '*.png'
declare module '*.svg'
declare module '*.md'

declare module 'paths.macro'
declare module 'intersection-observer'
declare module 'react-storybook-addon-props-combinations'
declare module 'react-syntax-highlighter'
declare module 'react-syntax-highlighter/dist/styles/prism'
